_target_: src.models.biobert_classifier.BioBERTClassifierModule
pretrained_path: dmis-lab/biobert-v1.1
with_lstm: false
train_size:
batch_size: 32
max_epochs: 20
lr: 0.00005 # 5e-5
warmup_epoch: 5
eps: 0.00000001 # 1e-8
weight_decay: 0.01
