_target_: src.models.graph_bert_model.GraphBertNodeClassificationModule
config:
  _target_: src.models.modules.graph_bert_layers.GraphBertConfig
train_size: 2326
batch_size: 32
max_epochs: 50
lr: 0.00005 # 5e-5
warmup_epoch: 5
eps: 0.00000001 # 1e-8
weight_decay: 0.01
