_target_: src.models.multi_modal_model.MultiModalModule
config:
  _target_: src.models.modules.graph_bert_layers.GraphBertConfig
  x_size: 1128
amino_vocab_size: 29
embedding_dim: 128
num_gnn_layers: 2
train_size: 2326
batch_size: 32
max_epochs: 20
lr: 0.00005 # 5e-5
warmup_epoch: 2
eps: 0.00000001 # 1e-8
weight_decay: 0.01
