_target_: src.datamodules.text_and_graph_datamodule.TextAndGraphModule
data_dir: ${data_dir}/bioinfer # data_dir is specified in config.yaml
pdb_processed_root: ${data_dir}/pdb_processed
batch_size: 16
pretrained_path: dmis-lab/biobert-v1.1
num_workers: 0
pin_memory: False
max_seq_len: 256
