_target_: src.datamodules.graph_datamodule.GraphDatasetModule
data_dir:
pdb_processed_root: ${data_dir}/pdb_processed
batch_size: 16
pretrained_path: dmis-lab/biobert-v1.1
num_workers: 0
pin_memory: False
max_seq_len: 256
