_target_: src.datamodules.graph_datamodule.GraphDatasetModule
csv_path:
pdb_path: ${data_dir}/pdb
thereshold: 8
batch_size: 16
pretrained_path: dmis-lab/biobert-v1.1
num_workers: 0
pin_memory: False
max_seq_len: 256
