_target_: src.datamodules.text_datamodule.TextDatasetModule
data_dir: ${data_dir}/hprd50 # data_dir is specified in config.yaml
batch_size: 16
pretrained_path: dmis-lab/biobert-v1.1
num_workers: 0
pin_memory: False
max_seq_len: 256
