_target_: src.datamodules.graph_node_classification_datamodule.GraphNodeClassificationDataModule
data_dir: ${data_dir}/hprd50 # data_dir is specified in config.yaml
pdb_processed_root: ${data_dir}/pdb_processed
k: 5
batch_size: 32
num_workers: 0
pin_memory: False
